sudo: required
dist: trusty
language: node_js
os:
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
cache: 
  directories:
    - node_modules
env:
  - NODE_VERSION="10.8.0"
before_install:
  - git clone https://github.com/xgeek-net/pipeline-release.git /tmp/.nvm
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
  - echo $CLIENT_SECRET | base64 -D > src/config/client.js
  - echo $MOCHA_SECRET | base64 -D > test/token.js
  # Prepare NodeGit
  - export npm_config_target=3.1.9
  - export npm_config_arch=x64
  - export npm_config_target_arch=x64
  - export npm_config_disturl=https://atom.io/download/electron
  - export npm_config_runtime=electron
  - export npm_config_build_from_source=true
install:
  - npm install
#before_script:
script:
  - NODE_ENV=test npm run coveralls
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
  - brew update
  - brew install bower
  - brew install makensis
  - bower install
  - npm run archive:mac
deploy:
  provider: releases
  api_key:
    secure: "mDS3fYMdhOW/aTUdW70pKNZ2ybAgfPKqcl3zNlP7+mVXnp0BqUmL7PqHubNVJlLNPTiuLt1czDWhxdrR1nJM1FUTfoEtnnuyck3UOjhekQXAohctc4KmC7x/2r3HWCCOsT4FOAcproTT/c8VfCaCVY7ycnKqHUOE1bm+QWJKmbjgkuy4W9SPDRMkQhNIuVvW8uY8tHEwKD6Nt21W8of9qLgLJ8Z6fUNa3XXVFzWj0IhNUXXYWY3MdMLPrbKKIzjpkrLftlSSn6BopyOXZMCa8RqYmOznMmjOy4Z7aGW0LeKy8ZNM6BLm5MBiCYJFTpmqUij2JsqX6KQyO957AmuO5fNs0sEjZjifFbnncoRIIHzfmu1H0BasIibhr+VZhY98Ad48xhsYhOObK0T09jus94uoDxhIb+gcmz+vWFzWiPIsiPU7BSrCQSENhQfvVXh9B5QN3wc6Ez5CWlz3RKxBLVxQaEcbtBCM8wMvDdU40jAuf8ZTu02QKa1XQVKGsAa/FKE+8K8/DgJYaxqSWznHDp2YMOlW1sfVEPxEs24B6nQvocQjWXjUBjD3MF3i+zwgZQXu1AQkmD2/rEracXi1Wr44XbTL4NW6ThnQYbxRWVI4gPLdhkGPlyuTp/vzHaIW+64IqT4F8j1PeKHR2neX3pWARHlnUKlthmbm/w7u+Gg="
  file:
    - build/dist/Pipeline-$TRAVIS_TAG-mac.zip
    - build/dist/Pipeline-$TRAVIS_TAG.dmg
  skip_cleanup: true
  on:
    repo: xgeek-net/pipeline
    tags: true
    branch: master